// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixrfudvmzzrkzrnclvbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4cmZ1ZHZtenpya3pybmNsdmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTI3NzgsImV4cCI6MjA3NDM2ODc3OH0.QnZjv980I9Q7PtaKnN1pKFcBUPIK4m4oIIGZ2QWRwDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});